package com.examples.grant_categories;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class GrantApplication implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Dollar Amount")
	private java.lang.Double dollarAmount;
	@org.kie.api.definition.type.Label(value = "Grant Categories")
	private java.util.List<java.lang.String> categories;

	public GrantApplication() {
	}

	public java.lang.Double getDollarAmount() {
		return this.dollarAmount;
	}

	public void setDollarAmount(java.lang.Double dollarAmount) {
		this.dollarAmount = dollarAmount;
	}

	public java.util.List<java.lang.String> getCategories() {
		return this.categories;
	}

	public void setCategories(java.util.List<java.lang.String> categories) {
		this.categories = categories;
	}

	public GrantApplication(java.lang.Double dollarAmount,
			java.util.List<java.lang.String> categories) {
		this.dollarAmount = dollarAmount;
		this.categories = categories;
	}

}